apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: quarkus-greeter
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: build-bot
          source:
            git:
              revision: "${git.source.revision}"
              url: "${git.source.repo.url}"
          steps:
            - args:
                - '/usr/local/bin/buildah.sh'
              env:
                - name: WORK_DIR
                  value: /workspace/java/quarkus
                - name: DESTINATION_NAME
                  value: ${app.container.image}
              image: quay.io/rhdevelopers/quarkus-java-builder
              name: docker-push
              volumeMounts:
                - mountPath: /root/.m2
                  name: m2-cache
              workingDir: /workspace/java/quarkus
          timeout: 60m
          volumes:
            - name: m2-cache
              emptyDir: {}
      revisionTemplate:
        metadata:
          labels:
            app:  quarkus-greeter
        spec:
          container:
            image: ${app.container.image}